name: LayerZeroVyper
dependencies:
  - name: SolidityExamples
    github: LayerZero-Labs/solidity-examples
    ref: main
    contracts_folder: contracts
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.2

plugins:
  - name: solidity
  - name: vyper

solidity:
  import_remapping:
    - "@layerzero=SolidityExamples/main"
    - "openzeppelin=OpenZeppelin/4.9.2"
